### ISSUE TITLE
Final checks of documentation

### ISSUE THREAD

**Issue by sarakonradi** [nest/nest-simulator#1445]
Below are the final documentation checks for the NEST 3.0 release:

* [x] Update conda environment #1411 
* [x] Create workflow page #1439  
* [x] Update Mac manual #1446 
* [x] User documentation extractor #1355
* [x] Update model docs #1374 #1530
* [x] Tidy up table of contents #1434 
* [x] Update microcircuit documentation #1444 
* [x] Improve visibility of conversion guide #1475
* [ ] Remove NEST 3.0 preview warnings #1503
* [x] Move Editor Support to doc #1460
* [x] Move topology documentation #1468
* [x] Improve rate-based models documentation #1484
* [x] Update MUSIC tutorial #1495 #1552
* [x] Move dependencies and fix broken image links #1501 
* [x] Finalize examples #1504 #1534
* [x] Add information about nest_vars.sh #1515
* [x] Fix broken Network models link #1517
* [x] Modernize random number generation doc #1440 @heplesser 
* [x] Update documentation on adding spatial masks #1476 @hakonsbm 
* [x] Update voltmeter documentation #1354 #1530 @jougs 
* [x] Review kernel status doc #1373 @morales-gregorio
* [x] Publish updated microcircuit documentation #1526
* [x] Revise NEST Server documentation @jougs #2022
* [x] Update PyNEST's help() function #1904

Ticked means the corresponding PR has been merged.

**Comment by terhorstd** [comment]
Update model docs should include #1467

**Comment by terhorstd** [comment]
For NEST3 a proper migration guide is very important, so things in #1450 need to be sorted out before the release.

**Comment by sarakonradi** [comment]
Removed #1511 from the list, as it does not belong to the NEST 3.0 milestone

**Comment by jougs** [comment]
I'm closing, as there's only one action item left, which can be easily tracked by the corresponding issue #1503.
