### ISSUE TITLE
Model documentation enhancement checklist

### ISSUE THREAD

**Issue by sarakonradi** [nest/nest-simulator#1620]
Following the merge of #1530, this meta-issue summarizes further enhancements that could, or should, be made to the model documentation: 

* [x] Avoid table scroll bars -> #1639
* [ ] Move ``Remarks:`` to description
* [ ] Remove remaining Doxygen syntax (e.g., ``@notes``)
* [X] ~Add additional column to parameter table (see #1605)~
  ➟ will be implemented by NESTML (see https://github.com/nest/nestml/issues/712)
* [ ] Update multiplication symbols (see #1605)
* [x] Rename ``spike_detector`` (depending on discussion outcome #1579)
* [x] Fix subscripts of ``ginzburg_neuron`` -> #1605
* [x] Remove devices from guides
* [x] Fix technical typos and spelling -> #1624

Ideally, this list will be split into a number of small PRs. 

@jougs Feel free to edit. @clinssen This might be interesting for you too.

**Comment by heplesser** [comment]
@jougs Ping

**Comment by jougs** [comment]
The remaining issues are addressed in #2246.
