### ISSUE TITLE
Enhance PyNEST microcircuit example documentation

### ISSUE THREAD

**Issue by sarakonradi** [nest/nest-simulator#1650]
Following the merge of #1526, this issue addresses further enhancements to the PyNEST microcircuit example:

- [x] Rename titles to "Cortical microcircuit example" -> #1841 
- [x] Update "Note on Parameters" subheading -> #1841 
- [x] Update links to files in ``pynest/examples/Potjans_2014`` -> #1847 
- [ ] Automatically generate parameter table out of ``network_params.py``

**Comment by heplesser** [comment]
@jessica-mitchell Ping!

**Comment by jessica-mitchell** [comment]
@jhnnsnk This is an old topic that I was not originally involved in but maybe you have some insights. Do you happen to know in what context this last point would be used? "Automatically generate parameter table out of network_params.py"  

Is a table useful to show in the documentation? Or Is this something to be added to the code so a user can get a table of their parameters, so they have an overview? Or something else?

**Comment by jessica-mitchell** [comment]
Closing this issue after discussion with @jhnnsnk that this last point will not be addressed in near future, and the idea requires more in depth investigation.
