### ISSUE TITLE
Dissolve `gh-pages` branch

### ISSUE THREAD

**Issue by terhorstd** [nest/nest-simulator#1659]
**Describe the flaw**
Currently developer documentation is outdated and not stored in an easily maintainable place.

**Suggest an improvement**
Documentation that is currently stored in the `gh-pages` branch should be moved to the respective places in the code or corresponding external modules. Outdated information shoud be removed or moved to a maintainable location and updated (e.g. neuron modeling documentation migrated to or reference NESTML).

**Supporting materials**

List of items to be migrated to other parts of the documentation. Assignees check the item / reference a PR when this is done.
Items marked for deletion are checked already, because they will be automatically removed with the branch once all items are ticked.

* [x] [`NEST_Contributor_Agreement.pdf`](https://github.com/nest/nest-simulator/blob/gh-pages/NEST_Contributor_Agreement.pdf) -> how to contribute? user docs  -> #1707
* [x] [`code_review_guidelines.md`](https://github.com/nest/nest-simulator/blob/gh-pages/code_review_guidelines.md)  -> basically remove, like "two reviewers" should go to contributing guide  -> #1707
* [x] [`coding_guidelines_c++.md`](https://github.com/nest/nest-simulator/blob/gh-pages/coding_guidelines_c++.m) -> should be somewhere visible, subpage of getting involved  -> #1707
* [x] [`coding_guidelines_sli.md`](https://github.com/nest/nest-simulator/blob/gh-pages/coding_guidelines_sli.md)  -> remove, irrelevant, still in history
* [x] [`continuous_integration.md`](https://github.com/nest/nest-simulator/blob/gh-pages/continuous_integration.md)   -> <s>better docs in any google search, replace with only nest-specific things like how warnings are handled, etc.</s> covered in #1837
* [x] [`development_workflow.md`](https://github.com/nest/nest-simulator/blob/gh-pages/development_workflow.md) 
  * [x]  -> remove (basic git workflow described in github help pages)  -> #1707
  * [x]  -> make sure *NEST-specific conventions* are mentioned in the "how to contribute" page  -> #1707
* [x] [`eclipse_workflow.md`](https://github.com/nest/nest-simulator/blob/gh-pages/eclipse_workflow.md)   -> some sub-page of getting involved (not top level) -> #1719  
* [x] [`xcode_workflow.md`](https://github.com/nest/nest-simulator/blob/gh-pages/xcode_workflow.md)   -> some sub-page of getting involved (not top level)
* [x] [`extension_modules.md`](https://github.com/nest/nest-simulator/blob/gh-pages/extension_modules.md)   -> nest-extension-module -> #1777 / [nest/nest-extension-module:#1](https://github.com/nest/nest-extension-module/issues/3)
* [x] [`git_migration_plans.md`](https://github.com/nest/nest-simulator/blob/gh-pages/git_migration_plans.md)   -> just wrong. delete
* [x] [`index.md`](https://github.com/nest/nest-simulator/blob/gh-pages/index.md)   -> mostly covered by RtD navigation, dissolve in other docs
* [x] [`model_conversion_3g_4g.md`](https://github.com/nest/nest-simulator/blob/gh-pages/model_conversion_3g_4g.md)   -> remove
* [x] [`model_conversion_5g.md`](https://github.com/nest/nest-simulator/blob/gh-pages/model_conversion_5g.md)   -> remove
* [x] [`multimeter_support.md`](https://github.com/nest/nest-simulator/blob/gh-pages/multimeter_support.md)   -> remove, will come from NESTML automatically
* [x] [`neuron_and_device_models.md`](https://github.com/nest/nest-simulator/blob/gh-pages/neuron_and_device_models.md)   -> nest-extension-module
* [x] [`synapse_models.md`](https://github.com/nest/nest-simulator/blob/gh-pages/synapse_models.md)   -> updated and integrated NESTML & nest-extension-module
* [x] [`neuron_model_naming.md`](https://github.com/nest/nest-simulator/blob/gh-pages/neuron_model_naming.md)   -> refactor, model directory intro **and** NESTML
* [x] [`synapse_model_naming.md`](https://github.com/nest/nest-simulator/blob/gh-pages/synapse_model_naming.md)   -> refactor, model directory intro **and** NESTML
* [x] [`stylesheets`](https://github.com/nest/nest-simulator/blob/gh-pages/stylesheets)   -> nice style, but not used anymore
* [x] [`synapses_overview.md`](https://github.com/nest/nest-simulator/blob/gh-pages/synapses_overview.md)   -> NEST concepts at the beginning of user-docs;  also create a page like this for neurons
* [x] [`tokens_and_datums.md`](https://github.com/nest/nest-simulator/blob/gh-pages/tokens_and_datums.md)   -> sli-dev docs, move to doxygen part of `token` and `datum` classes
* [x] [`variables_parameters_naming.md`](https://github.com/nest/nest-simulator/blob/gh-pages/variables_parameters_naming.md)    -> NESTML documentation
